            var lyrics = [{lyric: "Take CS50", time_after: 0}, 
                      {lyric: "I gave a chance to this class", time_after: 5000},
                      {lyric: "Went for the A, know I'll pass", time_after: 2000},                        
                    {lyric: "He'll tear those phone books in half", time_after: 2000}, 
                    {lyric: "And that's when you'll want more", time_after: 2000},
                    {lyric: "You'll code your psets in C", time_after: 2000}, 
                    {lyric: "And learn to love PHP", time_after: 2000},
                    {lyric: "Hash tables, binary trees", time_after: 2000},
                    {lyric: "Tonight don't dump your core", time_after: 2000}, 
                    {lyric: "Yo, David Malan", time_after: 2000}, //21
                    {lyric: "Walkthroughs, I'm not bailin'", time_after: 2000}, //23
                    {lyric: "Office hours, no one's failin'", time_after: 2000},
                    {lyric: "Where you think you're coding, baby?", time_after: 2000}, //27, 
                    {lyric: "Hey, I just met you", time_after: 2000}, //29, 
                    {lyric: "And this is crazy", time_after: 2500}, //31.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //33.5, 
                    {lyric: "Take CS50", time_after: 2000}, //35.5, 
                    {lyric: "It's hard to code right", time_after: 2000}, //37.5, 
                    {lyric: "Without you baby", time_after: 2000}, //39.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //41.5, 
                    {lyric: "Take CS50", time_after: 2000}, //43.5, 
                    {lyric: "Hey, I just met you", time_after: 2000}, //45.5, 
                    {lyric: "And this is crazy", time_after: 2500}, //47.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //49.5, 
                    {lyric: "Take CS50", time_after: 2000}, //51.5
                    {lyric: "And every other class", time_after: 2000}, //53.5, 
                    {lyric: "Tries to copy", time_after: 2000}, //55.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //57.5, 
                    {lyric: "Take CS50", time_after: 2000}, //59.5, 
                    {lyric: "We take our time with some Scratch", time_after: 5250}, 
                    {lyric: "For loops, events we would match", time_after: 2000}, 
                    {lyric: "Compiling using our bash", time_after: 2000}, 
                    {lyric: "This term won't be a bore", time_after: 2000}, 
                    {lyric: "We hack, and fund some free meals", time_after: 2000}, 
                    {lyric: "Lectures are simply unreal", time_after: 2000}, 
                    {lyric: "Our fair is such a big deal,", time_after: 2000}, 
                    {lyric: "There's so much to adore", time_after: 2000}, 
                    {lyric: "Yo, David Malan", time_after: 2000}, //21
                    {lyric: "Walkthroughs, I'm not bailin'", time_after: 2000}, //23
                    {lyric: "Office hours, no one's failin'", time_after: 2000},
                    {lyric: "Where you think you're coding, baby?", time_after: 2000}, //27, 
                    {lyric: "Hey, I just met you", time_after: 2000}, //29, 
                    {lyric: "And this is crazy", time_after: 2500}, //31.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //33.5, 
                    {lyric: "Take CS50", time_after: 2000}, //35.5, 
                    {lyric: "It's hard to code right", time_after: 2000}, //37.5, 
                    {lyric: "Without you baby", time_after: 2000}, //39.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //41.5, 
                    {lyric: "Take CS50", time_after: 2000}, //43.5, 
                    {lyric: "Hey, I just met you", time_after: 2000}, //45.5, 
                    {lyric: "And this is crazy", time_after: 2500}, //47.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //49.5, 
                    {lyric: "Take CS50", time_after: 2000}, //51.5
                    {lyric: "And every startup firm", time_after: 2000}, //53.5, 
                    {lyric: "Wants to hire me", time_after: 2000}, //55.5, 
                    {lyric: "Another reason", time_after: 2000}, //57.5, 
                    {lyric: "Take CS50", time_after: 1500}, //59.5,
                    {lyric: "Before you came into my life", time_after: 2000}, //59.5,
                    {lyric: "I coded so bad", time_after: 2000}, //59.5,
                    {lyric: "I coded <i>so</i> bad", time_after: 2000}, //59.5,
                    {lyric: "I coded so, so bad", time_after: 1800}, //59.5,
                    {lyric: "Before you came into my life", time_after: 2000}, //59.5,
                    {lyric: "I coded so bad", time_after: 2000}, //59.5,
                    {lyric: "And I can't go back", time_after: 2000}, //59.5,
                    {lyric: "I coded so, so bad", time_after: 2000}, //59.5,
                    {lyric: "It's hard to code right", time_after: 10000}, //37.5, 
                    {lyric: "Without you baby", time_after: 2000}, //39.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //41.5, 
                    {lyric: "Take CS50", time_after: 2000}, //43.5, 
                    {lyric: "Hey, I just met you", time_after: 2000}, //53.5, 
                    {lyric: "And this is crazy", time_after: 2000}, //55.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //57.5, 
                    {lyric: "Take CS50", time_after: 2000}, //59.5, 
                    {lyric: "It's hard to code right", time_after: 2000}, //37.5, 
                    {lyric: "Without you baby", time_after: 2000}, //39.5, 
                    {lyric: "But here's our reason", time_after: 2000}, //41.5, 
                    {lyric: "Take CS50", time_after: 2000}, //43.5, 
                    {lyric: "Before you came into my life", time_after: 2000}, //59.5,
                    {lyric: "I coded so bad", time_after: 2000}, //59.5,
                    {lyric: "I coded <i>so</i> bad", time_after: 2000}, //59.5,
                    {lyric: "I coded so, so bad", time_after: 2000}, //59.5,
                    {lyric: "Before you came into my life", time_after: 2000}, //59.5,
                    {lyric: "I coded so bad", time_after: 2000}, //59.5,
                    {lyric: "And I can't go back", time_after: 2000}, //59.5,
                    {lyric: "Take CS50!", time_after: 2000}, //59.5,

                     ];